const { app, BrowserWindow, ipcMain, dialog, session } = require("electron");
const path = require("path");
const os = require("os");
const fs = require("fs");
const { spawn } = require("child_process");

const isWin = process.platform === "win32";
const isMac = process.platform === "darwin";

// --- Resolve bundled binary paths ---
function getBinariesDir() {
  if (app.isPackaged) {
    return path.join(process.resourcesPath, "bin");
  } else {
    return path.join(__dirname, "..", "resources", "bin");
  }
}

function getYtDlpPath() {
  const binDir = getBinariesDir();
  if (isWin) return path.join(binDir, "win", "yt-dlp.exe");
  if (isMac) return path.join(binDir, "mac", "yt-dlp");
  return path.join(binDir, "linux", "yt-dlp");
}

function getFfmpegDir() {
  const binDir = getBinariesDir();
  if (isWin) return path.join(binDir, "win");
  if (isMac) return path.join(binDir, "mac");
  return path.join(binDir, "linux");
}

const COOKIES_PATH = path.join(
  os.homedir(),
  "Documents",
  "yt-dlp-app",
  "cookies.txt",
);

let activeDownload = null;
let mainWindow = null;

function cookiesExist() {
  return fs.existsSync(COOKIES_PATH);
}

function cookieArgs() {
  return cookiesExist() ? ["--cookies", COOKIES_PATH] : [];
}

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1100,
    height: 720,
    minWidth: 900,
    minHeight: 600,
    titleBarStyle: "hiddenInset",
    backgroundColor: "#0a0a0f",
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
    },
  });

  if (process.env.NODE_ENV === "development") {
    mainWindow.loadURL("http://localhost:5173");
    mainWindow.webContents.openDevTools();
  } else {
    mainWindow.loadFile(path.join(__dirname, "../dist/index.html"));
  }

  return mainWindow;
}

app.whenReady().then(() => {
  const win = createWindow();

  // Ensure cookies directory exists
  const cookiesDir = path.dirname(COOKIES_PATH);
  if (!fs.existsSync(cookiesDir)) {
    fs.mkdirSync(cookiesDir, { recursive: true });
  }

  console.log("[bin] yt-dlp path:", getYtDlpPath());
  console.log("[bin] yt-dlp exists:", fs.existsSync(getYtDlpPath()));
});

app.on("window-all-closed", () => {
  if (!isMac) app.quit();
});

// --- YouTube Login Window ---
function openYouTubeLogin() {
  return new Promise((resolve) => {
    const loginWin = new BrowserWindow({
      width: 500,
      height: 650,
      title: "Sign in to YouTube",
      parent: mainWindow,
      modal: true,
      webPreferences: {
        contextIsolation: true,
        nodeIntegration: false,
      },
    });

    loginWin.loadURL(
      "https://accounts.google.com/signin/v2/identifier?service=youtube",
    );

    // Watch for navigation to YouTube after successful login
    loginWin.webContents.on("did-navigate", async (event, navUrl) => {
      if (
        navUrl.includes("youtube.com") &&
        !navUrl.includes("accounts.google.com")
      ) {
        console.log("[auth] Logged in, extracting cookies...");

        try {
          // Get all cookies from the login session
          const cookies = await loginWin.webContents.session.cookies.get({
            domain: ".youtube.com",
          });

          // Also get google cookies
          const googleCookies = await loginWin.webContents.session.cookies.get({
            domain: ".google.com",
          });

          const allCookies = [...cookies, ...googleCookies];

          // Write cookies in Netscape format that yt-dlp understands
          const cookieLines = [
            "# Netscape HTTP Cookie File",
            "# This file was generated by yt-dlp-app",
            "",
          ];

          for (const cookie of allCookies) {
            const domain = cookie.domain.startsWith(".")
              ? cookie.domain
              : "." + cookie.domain;
            const flag = cookie.domain.startsWith(".") ? "TRUE" : "FALSE";
            const secure = cookie.secure ? "TRUE" : "FALSE";
            const expiry = cookie.expirationDate
              ? Math.floor(cookie.expirationDate)
              : 0;
            cookieLines.push(
              `${domain}\t${flag}\t${cookie.path}\t${secure}\t${expiry}\t${cookie.name}\t${cookie.value}`,
            );
          }

          fs.writeFileSync(COOKIES_PATH, cookieLines.join("\n"));
          console.log("[auth] Cookies saved:", allCookies.length, "cookies");

          loginWin.close();
          resolve(true);
        } catch (err) {
          console.error("[auth] Failed to extract cookies:", err);
          loginWin.close();
          resolve(false);
        }
      }
    });

    loginWin.on("closed", () => {
      resolve(false);
    });
  });
}

// --- IPC: Open YouTube login ---
ipcMain.handle("open-youtube-login", async () => {
  const success = await openYouTubeLogin();
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send("cookies-status", success);
  }
  return success;
});

// --- Check cookies status ---
ipcMain.handle("get-cookies-status", () => cookiesExist());

// --- Clear cookies (force re-login) ---
ipcMain.handle("clear-cookies", () => {
  if (cookiesExist()) {
    fs.unlinkSync(COOKIES_PATH);
  }
  return true;
});

// --- Get Video Info ---
ipcMain.handle("get-video-info", async (_, url) => {
  return new Promise((resolve, reject) => {
    let output = "";
    let errorOutput = "";
    const args = [
      "--dump-json",
      "--no-playlist",
      "--js-runtimes",
      "node",
      ...cookieArgs(),
      url,
    ];
    const proc = spawn(getYtDlpPath(), args);

    proc.stdout.on("data", (d) => (output += d.toString()));
    proc.stderr.on("data", (d) => {
      errorOutput += d.toString();
      console.error(d.toString());
    });
    proc.on("error", (err) => {
      reject(new Error(`Failed to start yt-dlp: ${err.message}`));
    });
    proc.on("close", (code) => {
      if (code !== 0) {
        // Check if it's an age restriction error
        const isAgeRestricted =
          errorOutput.includes("Sign in to confirm your age") ||
          errorOutput.includes("age-restricted") ||
          errorOutput.includes("inappropriate for some users");

        if (isAgeRestricted) {
          return reject(new Error("AGE_RESTRICTED"));
        }

        return reject(new Error(`yt-dlp failed: ${errorOutput.slice(0, 300)}`));
      }
      try {
        const data = JSON.parse(output);
        const seen = new Set();
        const formats = [];

        const merged = data.formats
          .filter((f) => f.vcodec !== "none" && f.acodec !== "none" && f.height)
          .sort((a, b) => b.height - a.height);

        for (const f of merged) {
          const key = `${f.height}`;
          if (!seen.has(key)) {
            seen.add(key);
            const vbr = f.vbr
              ? Math.round(f.vbr)
              : f.tbr
                ? Math.round(f.tbr)
                : null;
            const abr = f.abr ? Math.round(f.abr) : null;
            formats.push({
              format_id: f.format_id,
              label:
                `${f.height}p${f.fps >= 60 ? ` ${f.fps}fps` : ""} · ${vbr ? vbr + " kbps" : ""} ${f.ext?.toUpperCase() || ""}`.trim(),
              resolution: `${f.width}×${f.height}`,
              vbitrate: vbr,
              abitrate: abr,
              fps: f.fps,
            });
          }
        }

        const videoOnly = data.formats
          .filter((f) => f.vcodec !== "none" && f.acodec === "none" && f.height)
          .sort((a, b) => b.height - a.height);

        const seenSplit = new Set();
        for (const f of videoOnly) {
          const key = `${f.height}-split`;
          if (!seenSplit.has(key)) {
            seenSplit.add(key);
            const vbr = f.vbr
              ? Math.round(f.vbr)
              : f.tbr
                ? Math.round(f.tbr)
                : null;
            formats.push({
              format_id: `bestvideo[height=${f.height}]+bestaudio`,
              label:
                `${f.height}p${f.fps >= 60 ? ` ${f.fps}fps` : ""} · ${vbr ? vbr + " kbps" : ""} (best quality)`.trim(),
              resolution: `${f.width}×${f.height}`,
              vbitrate: vbr,
              fps: f.fps,
            });
          }
        }

        resolve({
          title: data.title,
          thumbnail: data.thumbnail,
          duration: data.duration,
          uploader: data.uploader,
          formats,
        });
      } catch (e) {
        reject(new Error("Failed to parse video info"));
      }
    });
  });
});

// --- Select Folder ---
ipcMain.handle("select-folder", async (event) => {
  const win = BrowserWindow.fromWebContents(event.sender);
  const result = await dialog.showOpenDialog(win, {
    properties: ["openDirectory"],
    defaultPath: path.join(os.homedir(), "Downloads"),
  });
  return result.canceled ? null : result.filePaths[0];
});

// --- Get Downloads Path ---
ipcMain.handle("get-downloads-path", () => {
  return path.join(os.homedir(), "Downloads");
});

// --- Download ---
ipcMain.handle(
  "download",
  async (event, { url, formatId, container, savePath }) => {
    return new Promise((resolve, reject) => {
      const win = BrowserWindow.fromWebContents(event.sender);

      const args = [
        "-f",
        formatId,
        "--merge-output-format",
        container,
        "--ffmpeg-location",
        getFfmpegDir(),
        "--js-runtimes",
        "node",
        ...cookieArgs(),
        "-o",
        path.join(savePath, "%(title)s.%(ext)s"),
        "--newline",
        url,
      ];

      const proc = spawn(getYtDlpPath(), args);
      activeDownload = proc;

      proc.stdout.on("data", (data) => {
        const line = data.toString();
        console.log(line);
        const match = line.match(/\[download\]\s+([\d.]+)%/);
        if (match) {
          const percent = Math.round(parseFloat(match[1]));
          win.webContents.send("download-progress", percent);
        }
      });

      proc.stderr.on("data", (d) => console.error(d.toString()));

      proc.on("error", (err) => {
        activeDownload = null;
        reject(new Error(`Failed to start yt-dlp: ${err.message}`));
      });

      proc.on("close", (code) => {
        activeDownload = null;
        if (code === 0) resolve();
        else reject(new Error(code === null ? "cancel" : "Download failed"));
      });
    });
  },
);

// --- Cancel Download ---
ipcMain.handle("cancel-download", () => {
  if (activeDownload) {
    activeDownload.kill("SIGTERM");
    activeDownload = null;
  }
});
